export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

alias ia="open $1 -a /Applications/iA\ Writer.app"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
