#!/bin/bash

source "$CONFIG_DIR/colors.sh"
PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar --bar position=top height=32 blur_radius=30 color=transparent

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:12.0"
  label.font="OperatorMono Nerd Font:Bold:12.0"
  icon.color=$ACCENT_COLOR
  label.color=$WHITE
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"


clock=(
          icon=󰥔 
          update_freq=20 
          script="$PLUGIN_DIR/clock.sh"
       )

sketchybar --add item clock right \
           --set clock "${clock[@]}" \

calendar=(
           icon=󰸘 
           update_freq=30 
           icon.color=0xfff9e2af 
           script="$PLUGIN_DIR/calendar.sh"
 )


sketchybar --add item calendar right \
           --set calendar "${calendar[@]}"\

volume=(
           script="$PLUGIN_DIR/volume.sh"
           icon.color=0xffcba6f7
)

sketchybar --add item volume right \
           --subscribe volume volume_change \
           --set volume "${volume[@]}"

media=(
           label.color=$ACCENT_COLOR \
           label.max_chars=20
           icon.padding_left=0
           icon.color=0xfff38ba8
           scroll_texts=on 
           icon=󰝚             
           background.drawing=off
           script="$PLUGIN_DIR/media.sh"
  )

sketchybar --add item media right \
           --set media "${media[@]}" \
           --subscribe media media_change

sketchybar --add item battery right \
           --set battery update_freq=120 \
                         script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

sketchybar --add item chevron left \
           --set chevron icon=󰧚  icon.color=0xff89b4fa label.drawing=off \
           --add item front_app left \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

  brackets=(
           background.padding_right=20
           background.padding_left= 20
           background.height=28
           background.corner_radius=20
           background.color=$BAR_COLOR
    )

sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        label="$sid" \
        click_script="aerospace workspace $sid" \
        script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

sketchybar --add bracket status clock calendar volume media battery right \
            --set status "${brackets[@]!}"


sketchybar --add bracket active chevron front_app  space.$sid left \
            --set active "${brackets[@]!}"

### sketchybar --add bracket space space left \
###             --set space "${brackets[@]!}"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
