[manager]
show_hidden = true

[opener]
image = [
  { run = 'open -a Preview "$@"', desc = "Preview", block = false },
]
pdf = [
  { run = 'open -a Preview "$@"', desc = "Preview", block = false },
]
spreadsheet = [
  { run = 'open -a "Microsoft Excel" "$@"', desc = "Excel", block = false },
]
text = [
  { run = 'nvim "$@"', desc = "Neovim", block = true },
]
markdown = [
  { run = 'nvim "$@"', desc = "Neovim", block = true },
  { run = 'open -a "iA Writer" "$@"', desc = "iA Writer", block = false },
]

[open]
rules = [
  { mime = "image/*", use = "image" },
  { mime = "application/pdf", use = "pdf" },
  { mime = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", use = "spreadsheet" },
  { mime = "text/csv", use = "spreadsheet" },
  { name = "*.md", use = "markdown" },
  { name = "*.mdx", use = "markdown" },
  { name = "*.astro", use = "text" },
  { name = "*.bash", use = "text" },
  { name = "*.cjs", use = "text" },
  { name = "*.css", use = "text" },
  { name = "*.fish", use = "text" },
  { name = "*.html", use = "text" },
  { name = "*.js", use = "text" },
  { name = "*.jsx", use = "text" },
  { name = "*.lua", use = "text" },
  { name = "*.rst", use = "text" },
  { name = "*.sh", use = "text" },
  { name = "*.toml", use = "text" },
  { name = "*.ts", use = "text" },
  { name = "*.tsx", use = "text" },
  { name = "*.txt", use = "text" },
  { name = "*.vue", use = "text" },
  { name = "*.zsh", use = "text" },
  { name = "*.py", use = "text" },
  { name = "*.pyi", use = "text" },
  { name = "*.pyw", use = "text" },
  { name = "*.mjs", use = "text" },
  { mime = "text/*", use = "text" },
]

